export { StickyHeader } from "./sticky-header";
export { HeroSection } from "./hero-section";
export { ProblemSection } from "./problem-section";
export { HowItWorksSection } from "./how-it-works-section";
export { TryPromptsSection } from "./try-prompts-section";
export { InstallSection } from "./install-section";
export { FAQSection } from "./faq-section";
export { FinalCTASection } from "./final-cta-section";
export { FooterSection } from "./footer-section";
